theme: jekyll-theme-minimal
title: Hello, my name is Matt | mattgooch.com
description: An experienced Technology Specialist with a demonstrated history of delivering innovative solutions. Outside of work I have a passion for riding bikes, push and motorised having cycled from London to Paris and raced across Europe raising money for charities along the way.
logo: /assets/img/matt.jpg