theme: jekyll-theme-minimal
title: Matt Gooch
description: An experienced Technology Specialist with a demonstrated history of delivering innovative solutions. Outside of work I have a passion for riding bikes, push and motorised. I've cycled from London to Paris and raced across Europe whilst raising money for charities.
logo: /assets/img/matt.jpg